version: '3.3'
services:
  my-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'

  online-cinema:
    image: piskuntech/online-cinema-microservice-springboot
#    build:
#      context: .

    restart: on-failure
    ports:
      - '80:8080'
    depends_on:
      - my-db

    environment:
      - DATABASE_HOST=my-db
      - DATABASE_USER=user
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=db
      - DATABASE_PORT=3306
      - SLEEP_LENGTH=5
      - SPRING_DATASOURCE_URL=jdbc:mysql://my-db:3306/db?createDatabaseIfNotExist=true